apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $.Release.Name }}-deployment
  labels:
    app: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: api
        image: {{ .Values.imageTag }}
        ports:
        - containerPort: 5000
        env:
        - name: DB_HOST
          value: "10.129.0.38"
        - name: STORAGE_TYPE
          value: "memory"
#         Server implementation is not ready for DB
        - name: TEST_DATA_PRELOAD
          value: "y"
        - name: AMUZE_GRAPHQL_API_URL
          value: {{ .Values.apiAmuzeUrl }}
