---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ $.Release.Name }}-swager-ingress
  namespace: {{ $.Release.Namespace }}
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt"
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/auth-type: basic
    nginx.ingress.kubernetes.io/auth-secret: basic-auth
    nginx.ingress.kubernetes.io/auth-realm: 'Authentication Required - swager'
    nginx.ingress.kubernetes.io/configuration-snippet: |
      proxy_set_header X-DEVICE-ID $http_X_DEVICE_ID;
spec:
  rules:
  - host: {{ .Values.host }}
    http:
      paths:
        - path: /ui/
          backend:
            serviceName: {{ $.Release.Name }}-svc
            servicePort: 80
  tls:
  - hosts:
    - {{ .Values.host }}
    secretName: {{ $.Release.Name }}-tls