apiVersion: v1
kind: Service
metadata:
  name: {{ $.Release.Name }}-svc
  namespace: {{ $.Release.Namespace }}
spec:
  selector:
    app: api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000